### ISSUE TITLE
[주간 목표] 고성현 week3 

### ISSUE THREAD

**Issue by sunko-seoul** [lawnmowing-programmer/algo#156]
## 📅 Period
2023-03-12 ~ 2023-03-18

## 📝  Todo

- [ ] #157

**Comment by minjae9610** [comment]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/33440010/224699722-c7bd70e4-0e65-4672-9ebb-2f9d5288622b.png">
날날짜 정보 입력 부탁드려요~

**Comment by sunko-seoul** [comment]
확인 했습니다!
