### ISSUE TITLE
[주간 목표] 김형훈의 주간 알고리즘 목표

### ISSUE THREAD

**Issue by cryscham123** [lawnmowing-programmer/algo#37]
## 📅 Period

2023-02-27 ~ 2023-03-05
## 📝  Todo

- [ ] #92
- [x] #44
- [x] #70

**Comment by minjae9610** [comment]
오른쪽 Projects에서 +2 more 클릭하면 기간 지정 가능해요!
![image](https://user-images.githubusercontent.com/33440010/221750966-60beda79-225d-42cc-bb27-9b555d9aa355.png)

**Comment by minjae9610** [comment]
@cryscham123 혹시 목표 기한 지났는데 #92 와 함께 더 진행하실것이 아니라면 close 부탁드려도 될까요?
