### ISSUE TITLE
[주간 목표]  이주현 week1 목표

### ISSUE THREAD

**Issue by way-code** [lawnmowing-programmer/algo#38]
## 📅 Period

2023-02-28 ~  2023-02-03

## 📝  Todo

- [x] #49

**Comment by minjae9610** [comment]
오른쪽 Projects에서 +2 more 클릭하면 기간 지정 가능해요!
![image](https://user-images.githubusercontent.com/33440010/221751111-72857dc7-a77a-41ec-b607-f132afe70ff6.png)

**Comment by way-code** [comment]
> 오른쪽 Projects에서 +2 more 클릭하면 기간 지정 가능해요!
> ![image](https://user-images.githubusercontent.com/33440010/221751111-72857dc7-a77a-41ec-b607-f132afe70ff6.png)

아하 감사합니다!

**Comment by minjae9610** [comment]
@way-code 완료한 issue는 close로 바꿔주세요
