### ISSUE TITLE
[주간 목표] 서동현 week1 주간목표

### ISSUE THREAD

**Issue by west-eastH** [lawnmowing-programmer/algo#39]
## 📅 Period
2023-02-28 ~ 2023-03-05

## 📝  Todo

- [x] #40

**Comment by minjae9610** [comment]
오른쪽에 프로젝트랑 마일스톤 정보 채워주시면 좋을 것 같아요!
![image](https://user-images.githubusercontent.com/33440010/221790742-24329e60-a5b1-48f5-bfec-10263ccdeaff.png)
