### ISSUE TITLE
하루에 solved.ac의 CLASS 2 두 문제 씩 풀기

### ISSUE THREAD

**Issue by west-eastH** [lawnmowing-programmer/algo#40]
- [x] #41
- [x] #51
- [x] #72
- [x] #77
- [ ] 2023-03-04
- [ ] 2023-03-05

**Comment by minjae9610** [comment]
프로젝트에 기간도 설정해주면 좋을 것 같아요!
![image](https://user-images.githubusercontent.com/33440010/221793717-c3f54e2c-f754-4bfc-a23b-e84af1c19b64.png)
![image](https://user-images.githubusercontent.com/33440010/221793836-dbda8b6d-ea08-4ec6-b9e4-bccdf71c7cda.png)
