### ISSUE TITLE
[주간 목표] 손슬기 week1

### ISSUE THREAD

**Issue by dev-zoha** [lawnmowing-programmer/algo#50]
## 📅 Period

2023-02-27 ~ 2023-03-05

## 📝  Todo

- [x] 백준 Python 14문제
- [x] git 설치 및 적응하기

**Comment by minjae9610** [comment]
프로젝트 기간 입력해주시고, 목표 세부 사항 라벨은 떼주세요 :)
![image](https://user-images.githubusercontent.com/33440010/221873884-6e8a1b6a-0355-4849-a30b-669e7c53f015.png)

**Comment by minjae9610** [comment]
@dev-zoha 완료한 issue는 close로 바꿔주세요
