### ISSUE TITLE
[주간 목표] 최호준 week1 목표

### ISSUE THREAD

**Issue by Hojun-Cho** [lawnmowing-programmer/algo#56]
## 📅 Period

2023-02-27 ~ 2023-03-05

## 📝  Todo

- [ ] 실버 2 이상 두 문제 씩 풀기

**Comment by minjae9610** [comment]
프로젝트 기간 지정 부탁드려요!
![image](https://user-images.githubusercontent.com/33440010/222124528-b682f245-1737-44c5-932e-2f18bd871931.png)
그리고, 기본 todo가 남아있어요 ㄷㄷ
![image](https://user-images.githubusercontent.com/33440010/222124649-21748825-3078-43d3-a667-9b7ce70c0208.png)
작성하실 때 Preview를 누르시면 내가 지금 작성하는게 어떻게 보일지 미리 확인할 수 있어요 👍

**Comment by Hojun-Cho** [comment]
정했습니다~ 감사합니다!

**Comment by minjae9610** [comment]
In Progress로 옮겨 드렸습니다~
